version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      -  static_volume:/opt/voicechatapp/static
      -  ./host/log/nginx:/var/log/nginx
    ports:
        - "80:80"
    depends_on:
        - web
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: local
      MYSQL_ROOT_PASSWORD: rootaccess
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic --no-input --clear && 
      daphne -b 0.0.0.0 -p 8000 voicechatapp.asgi:application"
    volumes:
      - ./voicechatapp/:/opt/voicechatapp/
      - ./voicechatapp/chat:/opt/voicechatapp/chat
      - static_volume:/opt/voicechatapp/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:7.2.4-bookworm
    ports:
      - "6379:6379"

volumes:
  db_data:
  static_volume: