version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: local
      MYSQL_ROOT_PASSWORD: rootaccess
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python /opt/voicechatapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./voicechatapp/:/opt/voicechatapp/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: